### ISSUE TITLE
CORS origin issue faced while trying to pull XML response from JS based application

### ISSUE THREAD

**Issue by babystepcoder** [OpenMobileAlliance/OMA_LwM2M_for_Developers#565]
This is continuation with the JIRA ticket, https://helpdesk.openmobilealliance.org/browse/OPEN-7979

I am trying to download the data from _https://www.openmobilealliance.org/api/lwm2m/v1/Object_ using the below snippet,

```
const baseUrl = 'https://www.openmobilealliance.org/api/';
var req = new XMLHttpRequest();
console.log( req );
req.onreadystatechange = function() {
	console.log( req.readyState );
	if (req.readyState === 4) {
		console.log( req.responseText );
		console.log( 'data:text/plain;charset=utf-u,' + encodeURIComponent( req.responseText ) );
		return req.responseText;
	}
};

req.open('GET', baseUrl + 'lwm2m/v1/Object' );
req.send(null);	
console.log( req );
return req;
```

but I am getting an error as shown in below screen shot, which is 200 ok for the call but there are no response data, in firefox, it says, 'cannot allow a request from scripts'.

The below issue is in firefox:
`SyntaxError: JSON.parse: end of data after property name when ':' was expected at line 1 column 16122 of the JSON data`
`Response body is not available to scripts (Reason: CORS Missing Allow Origin)`

in both firefox and chrome:
in the developer in browser, under the network tab, under 'Transferred' column `'CORS Missing Allow Origin' ` and size is, `7.38 KB`

I have also tried,

`helm install <pod_name> <pod_name>-2305.0.0-20230606132233692.tgz -f PATH/values.yaml -f PATH/secrets.yaml --debug --set extraargs="-Dhttps://www.openmobilealliance.org.com=443 -Dcom.kiki.log=DEBUG"`

and also editing the ingress file, as given in,

In values.yaml:

```
ingress:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
```
Please suggest a solution and looking forward for your guidance... and prompt us if this is a good practice to configure CORS origin and trying to display the data inside an javascript application .
